<a href="https://colab.research.google.com/github/above-avg/pytorchblitz/blob/main/pytorchblitz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Tensors in Pytorch

In [ ]:
import torch
import numpy as np

In [ ]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [ ]:
np_array =  np.array(data)
x_np = torch.from_numpy(np_array)

In [ ]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]])

Random Tensor: 
 tensor([[0.8258, 0.3626],
        [0.2661, 0.5532]]) 



In [ ]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensors : \n {rand_tensor}\n")
print(f"Ones Tensor: \n {ones_tensor}\n")
print(f"Zeros Tensor: \n {zeros_tensor}\n")

Random Tensors : 
 tensor([[0.2086, 0.7353, 0.0478],
        [0.5218, 0.7553, 0.8060]])

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])



In [ ]:
tensor = torch.rand(3,4)

print(f"Shape of the tensor {tensor.shape}")
print(f"Dtype of the tensor {tensor.dtype}")
print(f"Device the tensor stored in: {tensor.device}")

Shape of the tensor torch.Size([3, 4])
Dtype of the tensor torch.float32
Device the tensor stored in: cpu


In [ ]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device, the tensor is on: {tensor.device}")

Device, the tensor is on: cuda:0


In [ ]:
tensor = torch.ones(4,4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
t1 = torch.cat([tensor,tensor,tensor],dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [ ]:
print(f"tensor.mul(tensor)\n {tensor.mul(tensor)}\n")
#alt syntax
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor)
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
print(f"tensor.matmul(tensor)\n {tensor.matmul(tensor)}\n")
# alt syntax
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor)
 tensor([[3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.]])

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [ ]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [ ]:
t.add_(1)
print(t)
print(n)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

In [ ]:
np.add(n, 1, out=n)

array([2., 2., 2., 2., 2.])

In [ ]:
print(t)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
print(n)

[2. 2. 2. 2. 2.]


# A gentle introduction to torch.autograd (works only on CPU)


In [ ]:
import torch
from torchvision.models import resnet18, ResNet18_Weights
model = resnet18(weights=ResNet18_Weights.DEFAULT)
data = torch.rand(1,3,64,64)
labels = torch.rand(1,1000)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth


100%|██████████| 44.7M/44.7M [00:00<00:00, 140MB/s]


In [ ]:
prediction = model(data) # forward pass

In [ ]:
loss = (prediction-labels).sum()
loss.backward() #backward pass

In [ ]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [ ]:
optim.step() #gradient descent

## Differentiation in Autograd

In [ ]:
import torch

a = torch.tensor([2.,3.], requires_grad=True)
b = torch.tensor([6.,4.], requires_grad=True)

In [ ]:
Q = 3*a**3 - b**2

In [ ]:
external_grad = torch.tensor([1.,1.])
Q.backward(gradient=external_grad)

In [ ]:
print(9*a**2 == a.grad)
print(-2*b == b.grad)

tensor([True, True])
tensor([True, True])


In [ ]:
x = torch.rand(5,5)
y = torch.rand(5,5)
z = torch.rand((5,5), requires_grad=True)

a = x+y
print(f"Does 'a' require gradients?: {a.requires_grad}")
b = x+z
print(f"Does 'b' require gradients?: {b.requires_grad}")

Does 'a' require gradients?: False
Does 'b' require gradients?: True


In [ ]:
from torch import nn, optim

model = resnet18(weights=ResNet18_Weights.DEFAULT)

#Freeze all the parameters in the network
for param in model.parameters():
  param.requires_grad = False

In [ ]:
model.fc = nn.Linear(512, 10)

In [ ]:
#Optimize only the classifier
optimizer = optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)